### ISSUE TITLE
Infinite loops should not crash pastebin

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#11]
In browsers, all of the UI runs in a single thread (HTML5 webworkers support multiple threads, but only for threads that do not access the DOM). Writing JS code with an infinite loop will cause the browser window to crash. 

To prevent this, one common approach is to rewrite Javascript to automatically insert timeouts. For example, this library will rewrite loops to check how long they have been executing and stop execution if a timeout has been exceeded: https://github.com/jsbin/loop-protect .

**Comment by venkat4541** [comment]
### Status Update - Checklist

- [x] Detect potential infinite loops
- [x] Warn user about the potential infinite loop
- [x] Point the line where the loop is present
- [ ] Prevent browser from freezing due such loops

**Comment by luminaxster** [comment]
Venkat, we use an AST anyways. I suggest instrumenting via Esprima AST and get the instrumented code with Escodegen. We are doing already doing it for other issues in execution trace.

**Comment by venkat4541** [comment]
Yes David, having tried to inject the timeout code to break the execution of loop, maybe its better we work together on this to simultaneously detect/prevent while tracing through AST.

**Comment by luminaxster** [comment]
#39 provides features for solving this. Insert timeout-call statement in loop blocks. Read executiontrace.js. more info in our team slack channel.

**Comment by venkat4541** [comment]
The updated code on my branch now detects and prevents code with infinite loops from running. Thus the browser isn't crashing. I had to add a run button which when pressed runs the code. The button gets disabled and the user gets a warning if there is any infinite loop.

Closing the issue till a better solution for this issue is found.
