### ISSUE TITLE
Toolbar icons should not be bold

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#118]
Bold styling is distracting and draws excess and unnecessary visual attention to the toolbar. 

![image](https://cloud.githubusercontent.com/assets/1881771/15905293/5ed12e32-2d82-11e6-826f-64a2cc57acf2.png)

**Comment by luminaxster** [comment]
Yup, I smooth it a notch:
![image](https://cloud.githubusercontent.com/assets/6577822/15917754/6c04bd9e-2dcd-11e6-93a4-ffbafe339f78.png)
Currently, deployed.
