### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#124]
Possible logo designs:

![image](https://cloud.githubusercontent.com/assets/1881771/15974978/3e6f8808-2f19-11e6-83f2-d4ad1df8fe97.png)

**Comment by luminaxster** [comment]
Option 1: ![image](https://cloud.githubusercontent.com/assets/6577822/16594286/b9e7dfd8-42b7-11e6-9aed-e441976440eb.png)

**Comment by tlatoza** [comment]
Maybe smaller font for <JS>? Does it need to be bold and italic? It currently has far more visual weight than the other pieces, making it seem to dominate the logo. Maybe make it more balanced?

**Comment by luminaxster** [comment]
Okidoki. I'll smooth it out. I'm worried about "JS" being in the logotype and the navigation bar. I will try other combinations.
Option 2: 
![image](https://cloud.githubusercontent.com/assets/6577822/16595279/68c49434-42bc-11e6-84fe-48ee2fe072c4.png)

**Comment by tlatoza** [comment]
I think the logo needs something that anchors it to programming and code, that makes it directly clear that this is for working with code. I don't see that <[World]> communicates that this is a website for working with code, and not, for example, some form of search engine.

**Comment by luminaxster** [comment]
I looked for a <[icon]> for JS but is <> or </>, and they don't look good with our logotype. 
This is Option 1 [revised]:
![image](https://cloud.githubusercontent.com/assets/6577822/16596963/5d831106-42c4-11e6-9932-1cfe9ec2a31b.png)

**Comment by tlatoza** [comment]
That's better.
