### ISSUE TITLE
Hovering over expression should display runtime value of expression

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#13]
Hovering over the value of an expression in the code editor should display a popup with its value. If the expression executed multiple times (i.e., in a loop or in a function invoked multiple times), the popup should let the user select which to display.

Mockup:
![image](https://cloud.githubusercontent.com/assets/1881771/12733527/512fdf40-c909-11e5-98f7-b1c5d955d1c7.png)

**Comment by luminaxster** [comment]
guys, check the Ace wiki for the tooltip code. You can populate it with your logic afterwards.
