### ISSUE TITLE
Add missing CSS styles to TreeViewExplorer

### ISSUE THREAD

**Issue by luminaxster** [tlatoza/SeeCodeRun#153]
We are missing the CSS styles from the CollapsibleLists library. other styles could be appended to src/traceView/trace-view.css

**Comment by hmir** [comment]
<img width="357" alt="stylized tree view" src="https://cloud.githubusercontent.com/assets/3443595/16874328/b2ccab32-4a66-11e6-8ce4-d257bdd8e8cc.png">

How's this?
