### ISSUE TITLE
Collect an execution trace

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#16]
Using source rewriting with a Esprima / Escodegen, rewrite the user's JS code before execution to automatically insert autolog calls wrapping every JS expression. 

e.g., 
var position = { x: oldPos.x, y: oldPos.y };
var newVal = foo(position);
if (newVal == param)
{

}
-->
var position = autolog({ x: log(oldPos.x, { PosData } ), y: autolog(oldPos.y, { PosData } ) });
var newVal = autolog(foo(autolog(position, { PosData } ), { PosData } ));
if (autolog(autolog(newVal, { PosData } ) == autolog(param, { PosData } ), { PosData } ))
{

}

The second parameter is an object encoding the location of the expression. Esprima provides information on the source location for every node in the abstract syntax tree. In this way, autolog records both the runtime value of each expression and the location of the expression in the original program text. 

The trace should also record the order in which each autolog statement is called. In this way, information about the execution path, whether statements did or did not execute, and which statements are executing on each iteration of a loop can be recorded.

**Comment by luminaxster** [comment]
We were able to insert non-recursive autologs. We need to use the editor to handle recursion as the call within a call finds the text moved. This corrupts the code. I will fix it today.

**Comment by luminaxster** [comment]
Forgot about Escodegen. On it.

**Comment by luminaxster** [comment]
#39 provides these features
