### ISSUE TITLE
Collapsing and connecting tree elements

### ISSUE THREAD

**Issue by luminaxster** [tlatoza/SeeCodeRun#161]
Do we have folding/ collapsing functionality?
https://seecode.run/#-KNG3y4JI_Iia4wOy605
There is an offset when an object is the last child of another object:
![image](https://cloud.githubusercontent.com/assets/6577822/17047943/f50f5f3c-4faf-11e6-88cc-d884636cb29a.png)

**Comment by hmir** [comment]
CollapsibleLists.apply() (which is called in tree-view-explorer.js) must be invoked when the popover loads, and not before. I wrapped that call in a 50ms timeout to make it work earlier, but it should really be based on an onLoad. I suspect this might also fix the offset issue.

**Comment by hmir** [comment]
Fixed tree-explorer:

<img width="264" alt="screen shot 2016-07-22 at 8 49 37 am" src="https://cloud.githubusercontent.com/assets/3443595/17057696/b9a63134-4fe9-11e6-9bb2-4385d661e319.png">
<img width="288" alt="screen shot 2016-07-22 at 8 49 58 am" src="https://cloud.githubusercontent.com/assets/3443595/17057699/c0c708da-4fe9-11e6-974e-805a5e996102.png">
