### ISSUE TITLE
Get runtime values for source location

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#17]
Given a source location (e.g., row and column in editor coordinates), determine the corresponding expression and return the expression. 

The corresponding expression should be the expression node lowest in the AST tree. For example, consider the following code.

var x = (y * 7) / z.

If the source location is the *, the corresponding expression will be (y * 7), as * is not an expression and (y * 7) / z is above (y * 7) in the expression tree.

**Comment by luminaxster** [comment]
#39 covers this case =]
