### ISSUE TITLE
Search execution trace

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#18]
Trace API should offer functionality for indexing the trace and letting clients search for matching expressions. For example, the user might search for all calls to JQuery methods that manipulate the DOM on the DOM element 'button5'. Support should be provided for querying based on both identifiers and runtime values.

**Comment by luminaxster** [comment]
Dana, here it is an example tha illustrates what we have to trace https://jsfiddle.net/luminaxster/g07c57o1/1/

**Comment by dana007** [comment]
Thanks, David. 
Perhaps, I did not make it clear. I understand the part you explained with examples. My question is trying to see how we will present the results. But, I guess it is for the Execution Visualization and I should not be too concerned.

**Comment by luminaxster** [comment]
Based in our session today:
TODO LIST
  0. Provide a list of test cases that we can agree on.
  1. Create a list of all JS (and Jquery) DOM API and classify them by read and write (getters and setters)
  2. Create a list of syntax types (look the full list in Syntax array defined at the beginning od esmorph.js)
  3. Analyze the stackdata entry stackDataEntry in line 18 of this file.
  4. Store statckdata in the JSLINQ format
  5. Provide queries that satisfy the API requirements

**Comment by dana007** [comment]
This issue was not meant to be in Sprint 2. We need to change the milestone.

**Comment by tlatoza** [comment]
TODO: make more specific and clarify what is part of milestone 4.
