### ISSUE TITLE
Runtime Javascript errors should show up in console

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#4]

**Comment by tlatoza** [comment]
https://danlimerick.wordpress.com/2014/01/18/how-to-catch-javascript-errors-with-window-onerror-even-on-chrome-and-firefox/

This code will echo all runtime errors (both those in the iframe and those outside) to the console:
		window.onerror = function(errorMsg, url, lineNumber) {
			console.log('Error: ' + errorMsg + '.  Line: ' + lineNumber);
			return false;
		}

**Comment by klein2ms** [comment]
this is implemented for the iframe (htmlviewer)

**Comment by tlatoza** [comment]
This still looks like it is an open issue on the current version.
