### ISSUE TITLE
Intercept the calls to console.log and print the output in Seecode.run console.

### ISSUE THREAD

**Issue by Alaboudi1** [tlatoza/SeeCodeRun#68]
This feature is already existed in Seeconde.run. However, it seems the way it is currently implemented does not work properly in Aurelia.

**Comment by luminaxster** [comment]
@klein2ms while I was working on getting the trace results, I notice that HtmlViewer creates an isolated page. I think we have to append the code from Aurelia before the [code script](https://github.com/tlatoza/SeeCodeRun/blob/master/src/htmlViewer/html-viewer.js#L69) and then collect them.

**Comment by klein2ms** [comment]
This issue is actually implemented in feature-68 branch.  waiting on final merges and then this is done.

**Comment by jbhilton11** [comment]
Will help out Steph fix leftover conflicts from merging the most recent master (includes ExecutionTrace) into her branch this afternoon.

**Comment by Alaboudi1** [comment]
I do not know if you guys are aware that feature-68 branch implementation brought back the closed issue #66 . This issue is fixed in the current master.
