### ISSUE TITLE
Console window doesn't log everything

### ISSUE THREAD

**Issue by jbhilton11** [tlatoza/SeeCodeRun#83]
For loop goes 10 times, and only 4 "Hello, world"'s show. 

![image](https://cloud.githubusercontent.com/assets/4753211/14404243/055aeebe-fe3f-11e5-83ab-680fbb0f8634.png)

**Comment by Alaboudi1** [comment]
Are sure this is not a css problem? I mean, the console dev might have an issue handling the overflow contents. So, the complete log is there, but is not showing in console log div.

**Comment by Alaboudi1** [comment]
Giving the console div this property : overflow: scroll;  might fix the problem.

**Comment by Alaboudi1** [comment]
Fixed in [issue-#83](https://github.com/tlatoza/SeeCodeRun/tree/issue-%2383)
