### ISSUE TITLE
Compile-time errors are not published.

### ISSUE THREAD

**Issue by luminaxster** [tlatoza/SeeCodeRun#86]
This [code](https://github.com/tlatoza/SeeCodeRun/blob/master/src/jsEditor/js-editor.js#L83) does not get invoked:
```javascript
 session.on('changeAnnotation',
      onAnnotationChanged);

    function onAnnotationChanged() {
      let annotations = session.getAnnotations();
      for (let key in annotations) {
        if (annotations.hasOwnProperty(key) && annotations[key].type === 'error') {
          ea.publish('onAnnotationChanged', {
            hasErrors: true,
            annotation: annotations[key]
          });
        }
      }
      ea.publish('onAnnotationChanged', {
        hasErrors: false,
        annotation: null
      });
    }
```
 I'm  using master's version.

As a result, this code is not invoked [either](https://github.com/tlatoza/SeeCodeRun/blob/master/src/jsEditor/js-editor.js#L144):
```javascript
 ea.subscribe('onAnnotationChanged', payload => {
      hasErrors = payload.hasErrors;
      if (payload.hasErrors) {
        console.log('has errors at: ' + payload.annotation);
      } else {
        console.log('no errors');
      }
    });
```
I am trying to avoid tracing the code if annotations are found (compile-time errors). So, I will subscribe to the event as shown above. I debugged js-editor and noticed this error.

**Comment by Alaboudi1** [comment]
You could just subscribe to this [event](https://github.com/tlatoza/SeeCodeRun/blob/master/src/consoleWindow/console-window.js#L28)

**Comment by Alaboudi1** [comment]
I thought you trace the code after the code is executed and not before? At least that what I have understood from our last talk. :)

**Comment by luminaxster** [comment]
That is one part of it. Overall, I rewrite user's code and then trace it. The issue I'm referring is about when receiving user's code, if it has errors I shouldn't trace it. The code I'm mentioning above is not running, so I cannot get information about errors in the code.
