### ISSUE TITLE
The jQuery library is not loaded properly for the chat functionality.

### ISSUE THREAD

**Issue by Alaboudi1** [tlatoza/SeeCodeRun#90]
![image](https://cloud.githubusercontent.com/assets/16814184/14514346/d5023056-01bd-11e6-9e60-31abb4322ceb.png)
When the pastebin is loaded for the first time,  it might throw an error as shown above. However, the error disappears after refreshing the page a couple of times.  I do not know the exact cause of such an error, but it seems it has something to do with how the jQuery library is loaded.

**Comment by klein2ms** [comment]
This appears to be fixed in the current master version
